### ISSUE TITLE
Finish Strict Codegen

### ISSUE THREAD

**Issue by andrew4328** [Lambda-Mountain-Compiler-Backend/lambda-mountain#282]
Bootstrap Sequence
* ✓ exit success
* ✓ exit early
* ✓ add numbers then exit
* ✓ local variables set / get
* ✓ global variables set / get
* ✓ function definition / call
* ✓ if
* ✓ while
* structs / enums
* match
* compile compiler

**Comment by andrew-johnson-4** [comment]
Push args:
* translate LocalVariable > expression locations to use new base pointer
* compile arg expression fragments
* if representation is StackVariable (do nothing)
* otherwise call 'push onto each non-stack-variable fragment
* insert push arg snippets into function call program body

**Comment by andrew-johnson-4** [comment]
Resolve and return context variables
