### ISSUE TITLE
ANSI C Frontend

### ISSUE THREAD

**Issue by andrew4328** [Lambda-Mountain-Compiler-Backend/lambda-mountain#467]
C is a lot easier to access than Rust etc.

```
import stdio.h;
```

**Comment by andrew-johnson-4** [comment]
This would be nice to see array vs field types actually look different in signature. Also function signatures would look a lot better.

**Comment by andrew-johnson-4** [comment]
This can start with just a header file parser, which is already useful.

**Comment by andrew-johnson-4** [comment]
```
cpp -include stdio.h /dev/null
```

**Comment by andrew4328** [comment]
* tokenize C
* parse C

c types can be prefixed as C_unsigned_char etc.

**Comment by andrew4328** [comment]
C type implication

```
C_signed_int => C_int
```
