### ISSUE TITLE
Compile to C

### ISSUE THREAD

**Issue by andrew4328** [Lambda-Mountain-Compiler-Backend/lambda-mountain#839]
Benefits of a C backend:
* instant cross-platform support
* great benchmark to compare performance of direct targets
* some extra nominal type checking (there is one outstanding error that this would catch)
* easy access to c libraries
* would prepare for an easy transition to "import stdio.h;" symbol import (just need to grok C symbol declarations)
* rearchitecting standard library would help clean up the awful state that things are in right now

**Comment by andrew-johnson-4** [comment]
Libraries:

```
lm/default.lm
c/default.lm
gnu-x86/default.lm
```

**Comment by andrew4328** [comment]
This really shouldn't be a large project. Only platform libraries need to update.

**Comment by andrew4328** [comment]
C Parts Working
* ✓ tokenization
* ✓ parsing
* ✓ preprocessing
* ✓ typechecking
* x compilation
