### ISSUE TITLE
install to /usr/local/bin only if sudo

### ISSUE THREAD

**Issue by andrew4328** [Lambda-Mountain-Compiler-Backend/lambda-mountain#859]
install to $HOME/bin otherwise

**Comment by alex-s168** [comment]
it should not install only if sudo, it should install if it has permissions to access that path

also I don't think anyone uses $HOME/bin 
Instead it should be $HOME/.local/bin

and if $HOME/.local/bin does not exist, it should create it

**Comment by andrew4328** [comment]
Ok, sounds reasonable.
