### ISSUE TITLE
main function has incorrect signature

### ISSUE THREAD

**Issue by alex-s168** [Lambda-Mountain-Compiler-Backend/lambda-mountain#945]
the generated main C function should take a int as first argument, but takes a unsigned long instead

**Comment by andrew4328** [comment]
Thanks, haven't read the generated C IR in a while. I would like for that to be more human readable eventually too.

**Comment by andrew4328** [comment]
I think "unsigned int" is safe right?

**Comment by alex-s168** [comment]
It has to be just `int` or otherwise clang errors

**Comment by andrew4328** [comment]
what about "char** argv" vs "char* argv[]"? equivalent?

**Comment by andrew4328** [comment]
I'll deploy the "int" in a second here, in case you are compiling this to check. I'll grab clang in the meanwhile.

**Comment by alex-s168** [comment]
> what about "char** argv" vs "char* argv[]"? equivalent?

I think

**Comment by andrew4328** [comment]
`clang` seems happy enough now. It is a bitter more pedantic than `gcc` by default.

I also added a smoke test that runs clang and gcc to check for errors. I get 2 warnings still, and will look into that.
