### ISSUE TITLE
Reduce compile times to under 5s

### ISSUE THREAD

**Issue by andrew4328** [Lambda-Mountain-Compiler-Backend/lambda-mountain#977]
This seems to be a periodic ticket. This time the culprit is unification being exponential instead of linear time for unification. An alphabetically sorted clause list would help make this quick.

**Comment by alex-s168** [comment]
I compiled LM with -O3 and I get this:
```
8.28%   _int_malloc
7.65%   __strcmp_evex
7.17%   .lookup ArrowU64ConsU64ConsStringHashtableEqU64String
7.13%   can-unify       ArrowU64ConsTypeType
5.99%   sizeof-type     ArrowU64Type
4.55%   __memmove_avx512_unaligned_erms
4.33%   unify   ArrowTContextConsListTypeListType
3.44%   substitute      ArrowListTypeConsListTypeTContext
3.41%   unify-inner     ArrowTContextConsTypeType
3.20%   typeof-var-raw  ArrowTypeConsStringConsTContextAST
2.61%   malloc
2.53%   find-alias      ArrowStringConsTypeString
2.30%   union   ArrowTContextConsTContextTContext
2.12%   .lookup ArrowListTupleTypeTypeConsListTupleTypeTypeConsTupleU64SmartStringHashtableEqListTupleTypeTypeTupleU64SmartString
1.95%   substitute      ArrowTypeConsTypeTContext
1.76%   can-unify       ArrowU64ConsListTypeListType
1.72%   fragment-context::lookup        ArrowFragmentConsU8ConsASTConsTypeConsStringFContext
1.14%   .lookup ArrowTypeConsTypeConsASTHashtableIsTypeAST
1.11%   .lookup ArrowTupleTypeTypeConsTupleTypeTypeConsStringHashtableEqTupleTypeTypeString
0.95%   strcmp@plt
...
```

**Comment by andrew4328** [comment]
I am aware of the top-down-level root cause also, which is exponential complexity of the unification algorithm. I am working on a quick fix and a long-term fix today.

**Comment by andrew4328** [comment]
Basically, A+B+C currently checks all permutations B+A+C etc. to unify. If the list is sorted in alphabetical order then time becomes linear.

**Comment by andrew4328** [comment]
This problem shot up to being a huge problem due to the longer conjugates with Fields `Field::0<A>+Field::1<B>+Field::2<C>` and there are some unused tags even.

**Comment by andrew4328** [comment]
Currently sitting at 15s on my desktop.

**Comment by alex-s168** [comment]
It's already under 5 seconds on my desktop

**Comment by andrew4328** [comment]
I think this was memory bound on my PC.
